# Generated by Django 5.1.6 on 2025-02-09 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validation In Progress'), ('validated', 'Validation Complete'), ('failed', 'Validation Failed')], default='uploaded', max_length=20)),
                ('row_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('passed', models.BooleanField()),
                ('error_count', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCERT.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('raw_data', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCERT.validationreport')),
            ],
        ),
    ]
